using System;
using System.Collections.Generic;
using System.Text;

namespace AppCD.Models
{
	class MedidasEspacio
	{
		public int question1 { get; set; }
		public int question2 { get; set; }
		public int question3 { get; set; }
		public int question4 { get; set; }
		public int question5 { get; set; }
		public int question6 { get; set; }
		public int question7 { get; set; }
		public int question8 { get; set; }
		public int question9 { get; set; }
		public int question10 { get; set; }
		public int question11 { get; set; }
		public int question12 { get; set; }
		public int question13 { get; set; }
		public int question14 { get; set; }
		public int question15 { get; set; }
		public int question16 { get; set; }
		public int question17 { get; set; }
		public int question18 { get; set; }
		public int question19 { get; set; }
		public int question20 { get; set; }
		public int question21 { get; set; }
		public int question22 { get; set; }
		public int question23 { get; set; }
		public int question24 { get; set; }
		public int question25 { get; set; }
		public int question26 { get; set; }
		public int question27 { get; set; }
		public int question28 { get; set; }
		public int question29 { get; set; }
		public int question30 { get; set; }
		public int question31 { get; set; }
		public int question32 { get; set; }
		public int question33 { get; set; }
		public int question34 { get; set; }
		public int question35 { get; set; }
		public int question36 { get; set; }
		public int question37 { get; set; }
		public int question38 { get; set; }
		public int question39 { get; set; }
		public int question40 { get; set; }
		public int question41 { get; set; }
		public int question42 { get; set; }
		public int question43 { get; set; }
		public int question44 { get; set; }
		public int question45 { get; set; }
		public int question46 { get; set; }
		public int question47 { get; set; }
		public int question48 { get; set; }
		public int question49 { get; set; }
		public int question50 { get; set; }
		public int question51 { get; set; }
		public int question52 { get; set; }
		public int question53 { get; set; }
		public int question54 { get; set; }
		public int question55 { get; set; }
		public int question56 { get; set; }
		public int question57 { get; set; }
		public int question58 { get; set; }
		public int question59 { get; set; }
		public int question60 { get; set; }
		public int question61 { get; set; }
		public int question62 { get; set; }
		public int question63 { get; set; }
		public int question64 { get; set; }
		public int question65 { get; set; }
		public int question66 { get; set; }
		public int question67 { get; set; }
		public int question68 { get; set; }
		public int question69 { get; set; }
		public int question70 { get; set; }
		public int question71 { get; set; }
		public int question72 { get; set; }
		public int question73 { get; set; }
		public int question74 { get; set; }
		public int question75 { get; set; }
		public int question76 { get; set; }
		public int question77 { get; set; }
		public int question78 { get; set; }
		public int question79 { get; set; }
		public int question80 { get; set; }
		public int question81 { get; set; }
		public int question82 { get; set; }
		public int question83 { get; set; }
		public int question84 { get; set; }
		public int question85 { get; set; }
		public int question86 { get; set; }
		public int question87 { get; set; }
		public int question88 { get; set; }
		public int question89 { get; set; }
		public int question90 { get; set; }
		public int question91 { get; set; }
		public int question92 { get; set; }
		public int question93 { get; set; }
		public int question94 { get; set; }
		public int question95 { get; set; }
		public int question96 { get; set; }
		public int question97 { get; set; }
		public int question98 { get; set; }
		public int question99 { get; set; }
		public int question100 { get; set; }
		public int question101 { get; set; }
		public int question102 { get; set; }
		public int question103 { get; set; }
		public int question104 { get; set; }
		public int question105 { get; set; }
		public int question106 { get; set; }
		public int question107 { get; set; }
		public int question108 { get; set; }
		public int question109 { get; set; }
	}
}
